project:
  type: website
  output-dir: docs

website:
  title: "Harrison Huang"
  navbar:
    right:
      - href: index.qmd
        text: About Me
      - text: Resume
        file: Harrison_resume2024.pdf
      - text: CV
        file: Data analyst CV.pdf
    page-footer:
      right:
        - icon: github
      border: true
      background: "light"
     
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual